# Generated by Django 5.2.17 on 2026-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_active_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Client opt-in for email notifications about their account/payments. Staff are always emailed.'),
        ),
    ]
