# Generated by Django 5.2.17 on 2026-09-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_contract',
        ),
    ]
