# Generated by Django 5.2.17 on 2026-09-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_active_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_account',
            field=models.BooleanField(default=False, help_text="Marks a shared, public-facing demo login (client or staff). Two things hinge on this flag, independent of the account's role: (1) profile/password-change endpoints refuse to modify it, since a demo visitor changing the password would lock out the next person who only knows the originally published credentials; (2) for a demo STAFF account specifically, admin_panel's permission decorators force every action to view-only regardless of what its role's RolePermission table grants — see admin_panel/decorators.py."),
        ),
    ]
