# Generated by Django 5.2.17 on 2026-08-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
