# Generated by Django 5.2.17 on 2026-08-15 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_lot_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='photos',
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='lots/photos/')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.lot')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
