# Generated by Django 5.2.17 on 2026-08-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_lot_photos_lotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, help_text='e.g. corner lot, mountain view, near clubhouse'),
        ),
    ]
