# Generated by Django 5.2.17 on 2026-08-15 10:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_lot_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='buyer_full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deadline',
            field=models.DateField(default=datetime.date.today, help_text='Date by which a contract must be signed, or the reservation lapses.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.lot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
