# Generated by Django 5.2.17 on 2026-09-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dismissed_by_client',
            field=models.BooleanField(default=False, help_text='Client explicitly gave up on this reservation from their own reservations list (distinct from it simply lapsing past its grace period on its own).'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extension_count',
            field=models.PositiveIntegerField(default=0, help_text="How many times the client has self-extended this reservation's deadline."),
        ),
    ]
