# Generated by Django 5.2.17 on 2026-09-11 08:08

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_reservation_dismissed_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='floor_plan',
            field=models.FileField(blank=True, null=True, storage=core.storage.get_public_media_storage, upload_to='lots/floor_plans/'),
        ),
        migrations.AlterField(
            model_name='lotimage',
            name='image',
            field=models.ImageField(storage=core.storage.get_public_media_storage, upload_to='lots/photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.get_public_media_storage, upload_to='projects/covers/'),
        ),
    ]
