# Generated by Django 6.1 on 2026-08-12 05:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=32, unique=True)),
                ('payment_plan_type', models.CharField(choices=[('full_payment', 'Full (one-time) Payment'), ('installment', 'Installment')], max_length=20)),
                ('total_contract_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('term_months', models.PositiveIntegerField(default=0, help_text='0 for full payment')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Annual %, if financed', max_digits=5)),
                ('penalty_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Late penalty as % of the overdue installment amount', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed / Fully Paid'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='draft', max_length=20)),
                ('contract_date', models.DateField()),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'sales_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_contracts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='properties.lot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='sales.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring (added to each installment)')], default='one_time', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='sales.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.contract')),
            ],
            options={
                'ordering': ['contract', 'installment_number'],
                'unique_together': {('contract', 'installment_number')},
            },
        ),
    ]
