# Generated by Django 5.2.17 on 2026-08-15 10:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_reservation_options_and_more'),
        ('sales', '0002_contract_buyer_email_contract_buyer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='properties.reservation'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Annual %, if financed', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='penalty_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('2.00'), help_text='Late penalty as % of the overdue installment amount', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0 for full payment'),
        ),
    ]
