# Generated by Django 5.2.17 on 2026-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_contract_reservation_alter_contract_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='soa_pdf',
            field=models.FileField(blank=True, help_text='Statement of Account — regenerated after every payment.', null=True, upload_to='contracts/soa/'),
        ),
    ]
