# Generated by Django 5.2.17 on 2026-08-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('sales', '0004_contract_soa_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='expense',
            field=models.OneToOneField(blank=True, help_text='The company expense created when this commission was released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='expenses.expense'),
        ),
    ]
