# Generated by Django 5.2.17 on 2026-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_commission_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='kind',
            field=models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment'), ('full_payment', 'Full Payment')], default='installment', max_length=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(help_text='0 for the down payment row, if any.'),
        ),
    ]
