# Generated by Django 5.2.17 on 2026-08-26 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_installment_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('gentle', 'Gentle'), ('firm', 'Firm'), ('formal', 'Formal'), ('manual', 'Manual')], max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('overdue_amount_snapshot', models.DecimalField(decimal_places=2, help_text='Total overdue balance across all unpaid installments at the moment this was sent.', max_digits=12)),
                ('oldest_days_overdue_snapshot', models.PositiveIntegerField(help_text='Days overdue on the single oldest unpaid installment at the moment this was sent.')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='sales.contract')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Null means this was sent automatically, not by a staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_payment_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
