# Generated by Django 5.2.17 on 2026-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_reservation_fee',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='document_footer_note',
            field=models.TextField(blank=True, help_text='Appears at the bottom of every generated Statement of Account and receipt.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reservation_hold_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
