# Generated by Django 5.2.17 on 2026-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_platformsettings_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_agent', 'Sales Agent'), ('accountant', 'Accountant')], max_length=20)),
                ('section', models.CharField(choices=[('projects', 'Projects'), ('lots', 'Lots'), ('reservations', 'Reservations'), ('contracts', 'Contracts'), ('payments', 'Payments'), ('expenses', 'Expenses'), ('cash_flow', 'Cash Flow'), ('commissions', 'Commissions'), ('reports', 'Reports'), ('clients', 'Clients')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit')], max_length=10)),
                ('can_access', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['section', 'action', 'role'],
                'unique_together': {('role', 'section', 'action')},
            },
        ),
    ]
