# Generated by Django 5.2.17 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='currency_symbol',
            field=models.CharField(default='₱', help_text='Displayed throughout the site and on all documents. Purely a display label — no conversion is ever applied.', max_length=5),
        ),
    ]
