# Generated by Django 5.2.17 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_stage1_days',
            field=models.PositiveIntegerField(default=7, help_text='Days overdue before a gentle payment reminder is sent.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_stage2_days',
            field=models.PositiveIntegerField(default=15, help_text='Days overdue before a firmer payment reminder is sent.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_stage3_days',
            field=models.PositiveIntegerField(default=30, help_text='Days overdue before a formal payment demand is sent.'),
        ),
    ]
