# Generated by Django 5.2.17 on 2026-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_platformsettings_reminder_stage1_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_body_firm',
            field=models.TextField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_body_formal',
            field=models.TextField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_body_gentle',
            field=models.TextField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_subject_firm',
            field=models.CharField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_subject_formal',
            field=models.CharField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='reminder_subject_gentle',
            field=models.CharField(blank=True, help_text='Leave blank to use the built-in default wording. Available placeholders: {buyer_name}, {contract_number}, {amount}, {days_overdue}, {company_name}, {support_email}', max_length=200),
        ),
    ]
