# Generated by Django 5.2.17 on 2026-09-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_platformsettings_reminder_body_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='max_reservation_extensions',
            field=models.PositiveIntegerField(default=2, help_text='How many times a client can self-extend a reservation stuck awaiting its fee, before staff intervention is required. Each extension adds one full reservation_hold_days period.'),
        ),
    ]
