# Generated by Django 5.2.17 on 2026-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_platformsettings_max_reservation_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='company_name',
            field=models.CharField(default='RealmOpus', max_length=200),
        ),
    ]
