# Generated by Django 5.2.17 on 2026-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='section',
            field=models.CharField(choices=[('projects', 'Projects'), ('lots', 'Lots'), ('reservations', 'Reservations'), ('contracts', 'Contracts'), ('payments', 'Payments'), ('expenses', 'Expenses'), ('cash_flow', 'Cash Flow'), ('commissions', 'Commissions'), ('reports', 'Reports'), ('clients', 'Clients'), ('chatbot', 'AI Chatbot'), ('testimonials', 'Testimonials'), ('inquiries', 'Inquiries')], max_length=20),
        ),
    ]
