# Generated by Django 5.2.17 on 2026-09-11 08:08

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_rolepermission_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.get_public_media_storage, upload_to='settings/'),
        ),
    ]
