# Generated by Django 5.2.17 on 2026-08-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Deposit or Cheque payments', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque payments only', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Bank Deposit transaction/reference number', max_length=128),
        ),
    ]
