# Generated by Django 5.2.17 on 2026-09-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_bank_name_payment_cheque_number_and_more'),
        ('properties', '0005_alter_reservation_options_and_more'),
        ('sales', '0007_paymentreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.contract'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', False), ('reservation__isnull', True)), models.Q(('contract__isnull', True), ('reservation__isnull', False)), _connector='OR'), name='payment_exactly_one_of_contract_or_reservation'),
        ),
    ]
