# Generated by Django 5.2.17 on 2026-09-03 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_reservation_alter_payment_contract_and_more'),
        ('properties', '0007_reservation_dismissed_by_client_and_more'),
        ('sales', '0007_paymentreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_exactly_one_of_contract_or_reservation',
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_reservation_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_reservation_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_reservation_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_reservation_payments', to='properties.lot'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('refund_needed', 'Refund Needed')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', False), ('pending_reservation_lot__isnull', True), ('reservation__isnull', True)), models.Q(('contract__isnull', True), ('pending_reservation_lot__isnull', True), ('reservation__isnull', False)), models.Q(('contract__isnull', True), ('pending_reservation_lot__isnull', False), ('reservation__isnull', True)), _connector='OR'), name='payment_exactly_one_of_contract_reservation_or_pending_lot'),
        ),
    ]
