# Generated by Django 5.2.17 on 2026-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_due_soon', 'Payment Due Soon'), ('payment_overdue', 'Payment Overdue'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('reservation_expiring', 'Reservation Expiring'), ('reservation_created', 'Reservation Created'), ('contract_completed', 'Contract Fully Paid'), ('general', 'General')], max_length=30),
        ),
    ]
