# Generated by Django 5.2.17 on 2026-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledgebaseentry_conversation_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebaseentry',
            options={'ordering': ['category', 'question'], 'verbose_name_plural': 'Knowledge base entries'},
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='category',
            field=models.CharField(choices=[('reservation', 'Reservation & Buying Process'), ('payment', 'Payment Plans & Pricing'), ('portal', 'Client Portal'), ('legal', 'Legal & Ownership'), ('general', 'Company / General')], default='general', max_length=20),
        ),
    ]
