# Generated by Django 5.2.17 on 2026-09-09 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_knowledgebaseentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text="Optional context shown under the name, e.g. 'Homeowner, Block 4' or 'Lot buyer, 2026'.", max_length=150)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Testimonials with the same order fall back to newest first.')),
                ('is_active', models.BooleanField(default=True, help_text='Visible on the public site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
