# Generated by Django 5.2.17 on 2026-09-09 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
        ('properties', '0007_reservation_dismissed_by_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, help_text="Where this was submitted from, e.g. 'homepage', 'contact_page'.", max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_lot', models.ForeignKey(blank=True, help_text='Set only if this inquiry was submitted in the context of a specific lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.lot')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
