# Generated by Django 5.2.17 on 2026-09-09 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(help_text='Short overview shown in the blog list and featured gallery.')),
                ('content', models.TextField(help_text='Full post content. Paragraph breaks are preserved; no HTML.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blogs/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text="Optional YouTube or Vimeo URL, embedded on the post's detail page.")),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text="Shown in the homepage's featured blogs section.")),
                ('published_at', models.DateTimeField(blank=True, editable=False, help_text='Set automatically the first time this post is published -- stays fixed after that, even if unpublished and republished later.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
