# Generated by Django 5.2.17 on 2026-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Full post content, authored through the rich-text editor. Stored as sanitized HTML (bleach-cleaned on save) -- safe to render directly on the public site.'),
        ),
    ]
