# Generated by Django 5.2.17 on 2026-09-11 08:08

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.storage.get_public_media_storage, upload_to='blogs/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.get_public_media_storage, upload_to='testimonials/'),
        ),
    ]
